# Generated by Django 4.0.6 on 2022-08-20 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ultimo_nome', models.CharField(max_length=150)),
                ('foto', models.ImageField(upload_to='fotos')),
            ],
        ),
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('modalidade', models.CharField(choices=[('Bacharelado', 'Bacharelado'), ('Licenciatura', 'Licenciatura'), ('Tecnológo', 'Tecnológo')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='orientador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ultimo_nome', models.CharField(max_length=150)),
                ('link_do_curriculo_lattes', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='tcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('ano_do_documento', models.IntegerField(verbose_name='ano_documento')),
                ('resumo', models.TextField()),
                ('arquivo_do_documento', models.FileField(upload_to='tccs')),
                ('palavras_chave', models.CharField(max_length=50)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcc.autor')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcc.curso')),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcc.orientador')),
            ],
        ),
    ]
